### ISSUE TITLE
Unknown GITHUB_REPOSITORY during building assets

### ISSUE THREAD

**Issue by iniznet** [joanrodas/plubo#40]
If we clone the repository using composer rather than as template, `GITHUB_REPOSITORY` does not exist in the environment as result unable to build assets.

```js
[bud@5.8.7] [bud] › ✖  Error executing boot for service project 
 Error: Unknown GITHUB_REPOSITORY.
    at Object.<anonymous> ([secure]/on-template.js:20:9)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .js] ([secure]/node_modules/ts-node/src/index.ts:1587:43)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at [secure]/node_modules/@roots/bud/lib/cjs/services/Project/index.js:132:67
    at async [secure]/node_modules/@roots/bud/lib/cjs/services/Project/index.js:132:19
Done in 2.50s.
```

**Comment by joanrodas** [comment]
I added "rm -rf on-template.js" on composer.json "post-create-project-cmd".

**Comment by iniznet** [comment]
Thanks, it's fixed the issue & able to build assets with the latest commit after `composer create-project`.
